# Generated by Django 3.1.4 on 2021-07-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashId', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=1000000)),
            ],
        ),
    ]
